INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE) VALUES (1001, 'admin', 'DJANGO COURSE', CURRENT_DATE(), FALSE);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE) VALUES (1002, 'admin', 'ANGULAR COURSE', CURRENT_DATE(), FALSE);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE) VALUES (1003, 'admin', 'JAVA COURSE', CURRENT_DATE(), FALSE);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE) VALUES (1004, 'admin', 'REACT COURSE', CURRENT_DATE(), FALSE);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE) VALUES (1005, 'admin', 'C# COURSE', CURRENT_DATE(), FALSE);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE) VALUES (1006, 'admin', 'PYTHON COURSE', CURRENT_DATE(), FALSE);